name: example
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: opszero/actions-cloudflare-dns@v3.0.2
        with:
          type: "A"
          name: "review.example.com"
          content: "8.8.8.8"
          ttl: 1
          proxied: true